### ISSUE TITLE
The glu.h header for the GLU dependency isn't accounted for in the build system

### ISSUE THREAD

**Issue by jwillikers** [freeglut/freeglut#153]
The CMake build system for FreeGLUT never confirms the existence of the `glu.h` include, which is an obvious requirement.
Unfortunately, CMake's `FindOpenGL` module only pulls in the GLU library and not the include directory for its header file.
I'm working on fixing this properly in CMake in [PR 9216](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/9216).

In addition to the deficiency in CMake, the dependency on GLU that is specified in the build system is incorrect since it is only explicitly used for the test cases.
Technically, the GLU dependency should be modeled as a dependency on the FreeGLUT target.

For the backstory on this, I'm trying to build FreeGLUT with a dependency on Mesa's GLU library when it is installed to a non-system location.
While CMake is capable of finding the library, it doesn't properly check for the `glu.h` file and add it to any include directories.
When it is fixed upstream, FreeGLUT will still need to accommodate much older versions of CMake which will require some explicit workarounds to find find the `glu.h` file and add it to the include directories used when building FreeGLUT.

**Comment by dcnieho** [comment]
Would you be willing to submit a pull request that, if i understand
correctly:
1. only checks the GLU requirement for the test cases, not when not
building those
2. makes something like your solution work on the much older CMake versions
we support

Thanks!
