### ISSUE TITLE
[BUG] Extracting freegluet-3.4.0 from tar file : freeglut

### ISSUE THREAD

**Issue by yeokaiwei** [freeglut/freeglut#157]
![Screenshot 2024-04-15 120241](https://github.com/freeglut/freeglut/assets/36597018/7ab36ca9-80cd-4607-a82e-10f7af9e2e57)

"An unexpected error is keeping you from copying the folder, If you continue to receive this error, you can use the error code to search for help with this problem.

Error 0x80070522: A required privilege is not held by the client.

android_toolchain.cmake
Type: CMAKE File
Date modified: 08-10-22, Sat 12:12 AM
Size: 0 bytes"

STEPS TO REPRODUCE
Occurs when you "Extract all" in Windows from the freeglut-3.4.0.tar.gz downloaded from https://github.com/freeglut/freeglut/releases/download/v3.4.0/freeglut-3.4.0.tar.gz

**Comment by jtsiomb** [comment]
I don't see how this is a freeglut problem. Try a different archive extraction tool (you didn't mention which one you're using), try extracting in a different directory, or try to re-download the file in case it's not downloaded correctly.
