### ISSUE TITLE
Generation success on Linux Mint Victoria (64b), but one demo don't run -> indexed_color

### ISSUE THREAD

**Issue by tdechaize** [freeglut/freeglut#162]
Hi,

After Windows, I generate Freeglut V4.3.0 on Linux Mint Victoria, with success (demos included) with compiler GCC, only with X11 interface.

But, after test of demos, one don't run (indexed_color) with this error :

  ERROR:  Internal error <FBConfig with necessary capabilities not found> in function fgOpenWindow

What's append ?
It seem fault in internal function of FG.

Thank's.

**Comment by tdechaize** [comment]
Hi,

Internal function in file "./x11/fg_window_x11.c", line 226.

Thank's.

**Comment by jtsiomb** [comment]
The actual error message is "ERROR:  Internal error <FBConfig with necessary capabilities not found> in function fgOpenWindow".

The capability in question which wasn't found, is indexed color visuals. The indexed color example program can't run if your X server doesn't support indexed color visuals.

**Comment by tdechaize** [comment]
Hi,

OK, it's clear. I will verify if my config support this or not.

Thank's.
