### ISSUE TITLE
Allow platforms to set the number of joysticks

### ISSUE THREAD

**Issue by mardy** [freeglut/freeglut#163]
The `MAX_NUM_JOYSTICKS` value is hardcoded to 2, but some platforms (especially consoles) support way more than that. I suggest moving this definition to `fg_internal.h` and allow platforms to override it.

**Comment by jtsiomb** [comment]
The joystick part of freeglut is in dire need of maintainance. It's entirely broken and disabled on some platforms, and the API is probably inadequate and might need extending to become really useful. I never used it or looked into it personally so I don't have a clear idea of what needs to be done, but if you're interested in improving it, please feel free to discuss changes and submit pull requests.

What you're suggesting seems very reasonable.
