### ISSUE TITLE
Latest release is more than 1 year old

### ISSUE THREAD

**Issue by mardy** [freeglut/freeglut#172]
Hi again :-)
  It would be helpful for devkitPro if there was a new tag on freeglut, given the addition of the GameCube/Wii backend. I guess it could be beneficial for others, too, since there have been quite a few commits since the last release.

**Comment by dcnieho** [comment]
Is you work in a state where its very releasable, or are there some more
features that would be better to implement in the current weeks first?

**Comment by mardy** [comment]
I've ported two games already, and at the moment I don't foresee any changes. Bugfixes and improvements can always happen, of course, but the ones that I had queued in the last weeks were just those three that I submitted yesterday.

In case you are interested in those two games:
- [Crack Attack!](https://github.com/mardy/crack-attack/releases/tag/1.1.14-0) (here's the [gameplay video](https://www.youtube.com/watch?v=1x1qHiWa7aY))
- [BillardGL](https://github.com/mardy/billardgl/releases/tag/1.75-0)

**Comment by mardy** [comment]
Oh, I just realised that I made a silly mistake when committing one of the last PRs. It worked locally on my PC for some weird reason, but it's wrong and broke the build in other projects: https://github.com/freeglut/freeglut/pull/173

**Comment by jtsiomb** [comment]
We could push a new release. Adding a new platform is a big enough change to warrant it.

**Comment by jtsiomb** [comment]
I tagged a release candidate, please check it and let me know if this is good for release on the ogc side (or any other issue you can think of): https://github.com/freeglut/freeglut/releases/tag/v3.6.0-rc1

**Comment by mardy** [comment]
Thanks @jtsiomb !
It's all fine, there's a new (harmless) warning that appeared due to my last PR, which can be fixed with this: https://github.com/freeglut/freeglut/pull/175

**Comment by jtsiomb** [comment]
Just released 3.6.0, enjoy!
