### ISSUE TITLE
glutBitmapCharacter() fails for me when texture mapping is enabled

### ISSUE THREAD

**Issue by trguhq** [freeglut/freeglut#183]
In my project "testglobe" (https://github.com/trguhq/testglobe/blob/main/drv_ogl.c line 196) text rendering with glutBitmapCharacter() is corrupted and partly fails when texture mapping is enabled. In Kilgard's GLUT this does not happen on any system I've tried. This happened on Linux on a Raspberry Pi (arm64) which I installed today with `apt-get install freeglut3-dev`.

If replicating this, "t" toggles texture mapping (the default is off). If enabled, the text mostly disappears.

**Comment by jtsiomb** [comment]
Thanks for the report, I'll try to find some time soon to look into this.

**Comment by jtsiomb** [comment]
I wrote a simple test program: [fgtextbug.tar.gz](https://github.com/user-attachments/files/17008932/fgtextbug.tar.gz)
It draws some white text at the top left, and a textured quad with a colorful xor pattern in the middle.

First I tested on GNU/Linux with an AMD GPU with current freeglut, and indeed the text was coming out rainbow-colored when texture mapping is enabled. But then I tried the same program with GLUT 3.7 and exactly the same thing happened.

Then I moved it over to an SGI Octane2 with VPro graphics, where I have GLUT 3.6 installed, and the text is coming out white as it should. Then I tried it with freeglut on the SGI machine and again the text is coming out white.

So it looks like this isn't a bug in freeglut, but rather a but in some OpenGL drivers out there. `glBitmap` should not be affected by texture mapping, but at least on amdgpu, and your raspberry pi GPU driver, apparently it is.

**Comment by trguhq** [comment]
Thanks for looking into that. Perhaps it is a bug with Mesa rather than the drivers?

**Comment by jtsiomb** [comment]
You're probably right, I just verified that the text comes out textured on a laptop with intel graphics, so the common denominator seems to be mesa.

**Comment by jtsiomb** [comment]
@trguhq I wrote a better test program and narrowed down what the buggy behavrior of mesa is: https://gitlab.freedesktop.org/mesa/mesa/-/issues/11884#note_3101069
