### ISSUE TITLE
cannot extract 2nd zip

### ISSUE THREAD

**Issue by programminglanguagegrasshopper** [freeglut/freeglut#189]
I extracted the .gz file, then there was another .gz file, but the last .gz file wouldn't be extracted neither from 7zip or WinRAR.

**Comment by jtsiomb** [comment]
I assume you mean in the release page. Only the tarball named freeglut-X.Y.Z.tar.gz where X.Y.Z stands for the version number, is the official release archive. The others are added automatically by github. You can ignore them.
